### ISSUE TITLE
Multichain Version 1.0  beta - node API issues 

### ISSUE THREAD

**Issue by smalaichami** [scoin/multichain-node#11]
Hi, Thanks for the API... We are running multichain 1.0 beta  and the following are the issues and need your help to fix or upgrade.. 

 multichain.listStreamKeyItems({
...             stream: "stream2",
...             key: "key001",
...             verbose: true
...             }, 
... 
...             (err, info) => {
... 
... repl.js:282
    top.outputStream.write((e.stack || e) + '\n');
       ^

TypeError: Cannot read property 'outputStream' of undefined
    at Domain.<anonymous> (repl.js:282:8)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:66:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:110:18)
    at process._fatalException (node.js:220:33)

![screenshot from 2017-04-04 12-04-47](https://cloud.githubusercontent.com/assets/23695244/24644356/ac7e92ce-1930-11e7-965f-f2a9148e9b58.png)

Thanks,
Saravana

**Comment by smalaichami** [comment]
Thanks. it's nodejs related issue. Fixed the issue by updating nodejs.
