### ISSUE TITLE
Error when running test

### ISSUE THREAD

**Issue by gravyplaya** [scoin/multichain-node#2]
/home/user/www/chain1/node_modules/multichain-node/test/test.js:3
const assert = require('assert');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
Exiting...

**Comment by scoin** [comment]
Which version of Node are you using? The package is written with ES6 syntax and requires node v. 4.0.0 or newer.
